import os

PAIRS = ["BTC", "ETH", "SOL", "XRP", "DOGE", "SUI", "NEAR", "OP", "APT", "LINK", "ZEC", "ARB"]

SCAN_INTERVAL_SECONDS  = 20
PRICE_INTERVAL_SECONDS = 1

TC_ADX_MIN     = 30
DEPTH_GATE_PCT = 60

MARGIN_HARD_CAP_USDC = 25000
DEFAULT_MARGIN_USDC  = 700
DEFAULT_LEVERAGE     = 10

PAPER_MODE = os.getenv("PAPER_MODE", "true").strip().lower() != "false"

COOLDOWN_SECONDS      = 3600
CONSECUTIVE_LOSS_STOP = 5

SL_PCT           = 0.03
TP1_R_MULTIPLIER = 1.5
TP2_R_MULTIPLIER = 2.0
TRAILING_TP_PCT  = 0.0015

LEVERAGE_TIER_HIGH = 10
LEVERAGE_TIER_MID  = 8
LEVERAGE_TIER_LOW  = 6

UNIVERSE_SCAN_ENABLED = False

HL_API_URL = "https://api.hyperliquid.xyz/info"
