import os

PAIRS = ["BTC", "ETH", "SOL", "XRP", "DOGE", "SUI", "NEAR", "OP", "APT", "LINK", "ZEC", "ARB"]

SCAN_INTERVAL_SECONDS = 10
PRICE_INTERVAL_SECONDS = 1

ALERT_THRESHOLD = 8
TC_MIN_SCORE = 6
TC_ADX_MIN = 25
DEPTH_GATE_PCT = 60

J5_LONG_GATE = 20
J5_SHORT_GATE = 80

MARGIN_HARD_CAP_USDC = 2500
DEFAULT_MARGIN_USDC = 700
DEFAULT_LEVERAGE = 10

PAPER_MODE = os.getenv("PAPER_MODE", "true").strip().lower() != "false"

SESSION_BONUSES = {
    "EU": 0.5,
    "US": 0.5,
    "ASIA": 0.0,
}

COOLDOWN_MINUTES = 30

HL_API_URL = "https://api.hyperliquid.xyz/info"
