import os

PAIRS = ["BTC", "ETH", "SOL", "XRP", "DOGE", "SUI", "NEAR", "OP", "APT", "LINK", "ZEC", "ARB"]

SCAN_INTERVAL_SECONDS  = 20
PRICE_INTERVAL_SECONDS = 1

TC_ADX_MIN     = 30
DEPTH_GATE_PCT = 60

ACCOUNT_BALANCE         = 10000
MARGIN_PER_TRADE        = 2000
MAX_SIMULTANEOUS_TRADES = 2
MARGIN_HARD_CAP_USDC    = 25000
# DEFAULT_MARGIN_USDC   = 700  # replaced by MARGIN_PER_TRADE
DEFAULT_LEVERAGE        = 10

PAPER_MODE = os.getenv("PAPER_MODE", "true").strip().lower() != "false"

COOLDOWN_SECONDS      = 3600
CONSECUTIVE_LOSS_STOP = 3
DAILY_LOSS_LIMIT      = -500

SL_PCT           = 0.03
TP1_R_MULTIPLIER = 1.5
TP2_R_MULTIPLIER = 2.0
TRAILING_TP_PCT  = 0.0025

LEVERAGE_TIER1 = 10
LEVERAGE_TIER2 = 15
LEVERAGE_TIER3 = 25

SESSION_FILTER_ENABLED = True
SESSION_WINDOWS = [("07:00", "16:00"), ("13:00", "22:00")]

BTC_REGIME_FILTER_ENABLED = True

UNIVERSE_SCAN_ENABLED = False

PAIR_ADX_OVERRIDES = {"NEAR": 42, "SUI": 40}

HL_API_URL = "https://api.hyperliquid.xyz/info"
