import os

PAIRS = ["BTC", "ETH", "SOL", "XRP", "DOGE", "SUI", "NEAR", "OP", "APT", "LINK", "ZEC", "ARB"]

SCAN_INTERVAL_SECONDS = 10
PRICE_INTERVAL_SECONDS = 1

ALERT_THRESHOLD = 8
TC_MIN_SCORE = 6
TC_ADX_MIN = 25
DEPTH_GATE_PCT = 60

J5_LONG_GATE = 20
J5_SHORT_GATE = 80

MARGIN_HARD_CAP_USDC = 25000
DEFAULT_MARGIN_USDC = 700
DEFAULT_LEVERAGE = 10

PAPER_MODE = os.getenv("PAPER_MODE", "true").strip().lower() != "false"

SESSION_BONUSES = {
    "EU": 0.5,
    "US": 0.5,
    "ASIA": 0.0,
}

COOLDOWN_MINUTES = 30

# ── Universe scanner ──────────────────────────────────────────────────────────
PROMOTED_SLOTS = 3
ROTATION_WINDOW_MINUTES = 120
UNIVERSE_SCAN_INTERVAL_MINUTES = 5
UNIVERSE_VOLUME_MIN_USD = 50_000_000
UNIVERSE_OI_MIN_USD = 10_000_000
UNIVERSE_FUNDING_MIN_ABS = 0.005
UNIVERSE_VOLUME_FALLBACK_MULTIPLIER = 0.5

HL_API_URL = "https://api.hyperliquid.xyz/info"
